version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    ports:
      - 8081:8080
    #   - 2345:2345 #delve debug normal
    #   - 4000:4000 #delve debug tests
    volumes:
      - ./backend/secrets/testing.env:/app/secrets/.env
    
    env_file: ./backend/secrets/testing.env
    depends_on:
      database:
        condition: service_healthy

  product:
    build:
      context: ./product
      dockerfile: ./docker/Dockerfile
    # ports:
      # - 8082:8080
    volumes:
      - ./product/secrets/testing.env:/app/secrets/.env
    env_file: ./product/secrets/testing.env
    depends_on:
      database:
        condition: service_healthy

  cart:
    build:
      context: ./cart
      dockerfile: ./docker/Dockerfile
    ports:
      - "50051:50051" 
    volumes:
       - ./cart/secrets/testing.env:/app/secrets/.env
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=redis_password
      - REDIS_DB=0
      - REDIS_DEFAULT_TTL=30m
      - GRPC_PORT=50051
      - HTTP_PORT=8080
    depends_on:
      redis:
        condition: service_healthy

  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - psql_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - database

  
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis_password --maxmemory 100mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  psql_data:
    # external: true
    # name: psql_data
  redis_data: